services:
  # Наш Flask-сайт
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # "Зеркало": файлы на компе = файлы в контейнере
    environment:
      - DATABASE_URL=postgresql://taskuser:taskpass@db:5432/taskdb
    depends_on:
      - db

  # База данных PostgreSQL
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
      POSTGRES_DB: taskdb
    volumes:
      - postgres_data:/var/lib/postgresql/data # Сохраняет базу при перезагрузке
    ports:
      - "5432:5432"

volumes:
  postgres_data: